CFLAGS=-ggdb3 -Wall -Werror -pedantic -std=gnu99 -Wwrite-strings

MY_OBJS=cards.o deck.o future.o input.o test-input.o

test-input: $(MY_OBJS)
	gcc -o test-input -no-pie -ggdb3 $(MY_OBJS) $(GIVEN_OBJS)

.PHONY: run clean

run:
	./test-input

clean:
	rm test-input cards.o deck.o future.o input.o test-input.o *~
